ALL: cschem.icns cpcb.icns

publish: ALL
	cp cschem.icns ../cschem/
	cp cpcb.icns ../cpcb/

clean:; rm -rf *.icns *.iconset

%.icns: %.iconset
	iconutil -c icns -o $@ $<

cpcb.iconset:;
	mkdir -p $@
	cp ../cpcb/cpcb.png $@/icon_128x128.png

cschem.iconset:;
	mkdir -p $@
	cp ../cschem/cschem.png $@/icon_128x128.png

.PHONY: cpcb.iconset cschem.iconset ALL publish


