on: 
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:
  
name: Build binaries on linux

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install requirements for building binary
        run: .github/get-build-requirements
      - name: Build binary
        run: make
      - name: Build .deb
        run: make deb
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-deb-package
          path: build/cschem*.deb
          retention-days: 1
  release:
    name: Publish installer
    runs-on: ubuntu-latest
    if: (github.ref_type == 'tag') && startsWith(github.ref, 'v')
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: linux-deb-package
      - name: Upload .deb
        uses: softprops/action-gh-release@v2
        with:
          files: cschem*.deb
          token: ${{github.TOKEN}}
